name: new_sara
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.1.7
  marquee: ^2.2.3
  permission_handler: ^12.0.1
  get: ^4.7.2
  dio: ^5.8.0+1
  share_plus: ^11.0.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  translator: ^1.0.3+1
  flutter_upi_india: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/